import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import {
  FormLayout,
  FormHeading,
  FormInput,
  FormFooter,
  FormControl,
  FormHeroImage,
} from "../src/components/general/formComponents";
import withPublic from "../src/utils/routes/withPublic";

function Login({ authContext }) {
  const { login } = authContext;

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleLogin = async (e) => {
    e.preventDefault();
    await login(email, password);
  };

  return (
    <div>
      <Head>
        <title>Login | Prominente</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <div className="flex">
        <FormHeroImage logoPos="top-8 left-8" />
        <FormLayout>
          <FormHeading
            header="Sign in to your account"
            subheader="So we can provide you with your hardware needs!"
          />
          <FormControl onSubmit={handleLogin}>
            <FormInput
              fieldLabel="Email Address"
              type="email"
              onChange={(e) => setEmail(e.target.value)}
            />
            <FormInput
              fieldLabel="Password"
              passwordCondition="(must be at least 6 characters)"
              type="password"
              onChange={(e) => setPassword(e.target.value)}
            />
            <button className="btn-primary-filled" type="submit">
              Login
            </button>
            <Link href="/forgot-password">
              <a className="hover:underline text-center">
                Forgot your password?
              </a>
            </Link>
          </FormControl>
          <FormFooter
            footer="Don't have an account?"
            href="/signup"
            type="Sign Up"
          />
        </FormLayout>
      </div>
    </div>
  );
}

export default withPublic(Login);
